{"authenticated":true,"name":"Admin Seed","email":"admin@congreso.com","user_id":"550e8400-e29b-41d4-a716-446655440014","claims":{"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier":"550e8400-e29b-41d4-a716-446655440014","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"admin@congreso.com","name":"Admin Seed","http://schemas.microsoft.com/ws/2008/06/identity/claims/role":"admin","nbf":"1760745151","exp":"1760759556","iss":"http://localhost:5019","aud":"http://localhost:5019"}}